// src/components/editor/DocumentPreview.js
//
// The "Document Preview" action — an exact-where-possible preview of the
// Free-form note across all four export formats (PDF, DOCX, HTML, Markdown),
// each generated by the SAME verified producer its direct download uses.
//
// This is deliberately NOT a second, approximate renderer for any format:
//   - PDF   -> buildFreeformPdfFile      (freeformExportPdf.js)
//   - HTML  -> buildFreeformHtmlFile     (exportUtils.js)
//   - MD    -> buildFreeformMarkdownFile (exportUtils.js)
//   - DOCX  -> buildFreeformDocxFile     (exportUtils.js) — the preview shows
//              the EXACT html-to-docx input as a labelled approximation
//              (browsers cannot render .docx natively); Download always sends
//              the real generated .docx Blob.
// All four are the same functions ExportMenu's direct download and
// ShareDialog's ZIP path already call — see docs/ARCHITECTURE.md → Document
// Preview for the full "one producer per format" note.
//
// ---------------------------------------------------------------------------
// State ownership
// ---------------------------------------------------------------------------
// One lifecycle entry PER FORMAT, held in React state and keyed by format (see
// documentPreview.js). The displayed entry is a lookup, never a separate slot
// that has to be kept in step with the selected format — which is what the
// first version got wrong: it decided whether to apply a transition by reading
// a `formatRef` that React had not reassigned yet, so selecting HTML, Markdown
// or DOCX skipped the begin-transition, left the slot at requestId 0, and then
// discarded the finished artifact as stale. Nothing rendered, and Download
// stayed disabled.
//
// A monotonic request id PER FORMAT plus a synchronous in-flight guard PER
// FORMAT stop duplicate jobs; the snapshot is captured synchronously BEFORE the
// first await; and a stale completion (a superseded request, or a snapshot that
// has since been replaced) can never settle a newer request's entry.
//
// Generation is LAZY: opening the dialog generates only PDF; another format
// generates once, on first selection, and its entry is reused for the lifetime
// of the open dialog and the current snapshot. Refresh invalidates every cached
// format, because they were all built from the snapshot Refresh replaces.
import React, { useCallback, useEffect, useRef, useState } from "react";
import { actionButtonClass } from "../../lib/interactionStyles";
import {
  buildFreeformDocxFile,
  buildFreeformHtmlFile,
  buildFreeformMarkdownFile,
} from "../../lib/exportUtils";
import {
  buildFreeformPdfFile,
  captureFreeformExportSnapshot,
} from "../../lib/freeformExportPdf";
import { freeformExportFailureMessage } from "../../lib/exportIdentity";
import { downloadExportFile } from "../../lib/templateExport";
import { createBlobPreviewUrlManager } from "../../lib/blobPreviewUrl";
import {
  DOCUMENT_PREVIEW_FORMAT,
  DOCUMENT_PREVIEW_FORMAT_ORDER,
  URL_MANAGED_PREVIEW_FORMATS,
  beginPreviewFor,
  createPreviewArtifact,
  createPreviewEntries,
  documentPreviewFailureMessage,
  invalidatePreviewEntries,
  isDisplayablePreviewArtifact,
  isFreeformPreviewAvailable,
  isPreviewReady,
  isPreviewRunning,
  isRenderablePreviewHtml,
  isRenderablePreviewText,
  previewEntryFor,
  settlePreviewFailureFor,
  settlePreviewSuccessFor,
  shouldGeneratePreview,
} from "../../lib/documentPreview";
import DocumentPreviewDialog from "./DocumentPreviewDialog";

// Raised when a producer returns something that cannot be displayed. It is
// caught by the same handler every other failure is, so a malformed artifact is
// REPORTED as a failed format rather than silently rendering an empty frame.
const UNRENDERABLE = "nw-document-preview-unrenderable";

/** Build one format's artifact through its one existing producer. */
async function buildDocumentPreviewArtifact({ format, snapshot, urlManager }) {
  const title = snapshot.noteTitle;
  const html = snapshot.html;

  if (format === DOCUMENT_PREVIEW_FORMAT.PDF) {
    const file = await buildFreeformPdfFile(snapshot);
    return createPreviewArtifact({
      format,
      filename: file.name,
      mimeType: "application/pdf",
      blob: file.blob,
      // The one format that needs an object URL: the browser's native PDF
      // viewer is driven by an iframe `src`, and the frame is not sandboxed.
      previewUrl: urlManager.set(file.blob),
    });
  }

  if (format === DOCUMENT_PREVIEW_FORMAT.HTML) {
    const file = await buildFreeformHtmlFile({ title, html });
    // The exact generated document string — the same bytes the Blob holds —
    // rendered through a sandboxed `srcDoc`. No object URL: a sandboxed iframe
    // has an opaque origin, and a browser will not dereference a `blob:` URL
    // into one, which is precisely why this preview used to come up blank.
    if (!isRenderablePreviewHtml(file.text)) throw new Error(UNRENDERABLE);
    return createPreviewArtifact({
      format,
      filename: file.name,
      mimeType: "text/html",
      blob: file.blob,
      previewHtml: file.text,
    });
  }

  if (format === DOCUMENT_PREVIEW_FORMAT.MARKDOWN) {
    const file = await buildFreeformMarkdownFile({ title, html });
    // The exact generated source string, never read back out of the Blob.
    if (!isRenderablePreviewText(file.text)) throw new Error(UNRENDERABLE);
    return createPreviewArtifact({
      format,
      filename: file.name,
      mimeType: "text/markdown",
      blob: file.blob,
      previewText: file.text,
    });
  }

  // DOCX: `blob` is the real generated .docx and is the only thing Download
  // ever sends. `previewHtml` is the EXACT input html-to-docx received, shown
  // as the clearly labelled approximation — a separate field, so the two can
  // never be confused for one another.
  const file = await buildFreeformDocxFile({ title, html });
  if (!isRenderablePreviewHtml(file.previewHtml)) throw new Error(UNRENDERABLE);
  return createPreviewArtifact({
    format,
    filename: file.name,
    mimeType:
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    blob: file.blob,
    previewHtml: file.previewHtml,
  });
}

export default function DocumentPreview({ source }) {
  const [open, setOpen] = useState(false);
  const [format, setFormat] = useState(DOCUMENT_PREVIEW_FORMAT.PDF);
  const [entries, setEntries] = useState(createPreviewEntries);

  const triggerRef = useRef(null);
  const mountedRef = useRef(true);

  // Read synchronously by event handlers, which run after the render that
  // produced this value — so it is never behind what is on screen.
  const entriesRef = useRef(entries);
  entriesRef.current = entries;

  // The current immutable snapshot every generation job reads from. Replaced
  // wholesale on open and on Refresh — never mutated.
  const snapshotRef = useRef(null);
  // Per-format monotonic request ids and in-flight guards — four independent
  // sequences, so generating HTML cannot be blocked by (or invalidate) a PDF
  // job.
  const requestIdsRef = useRef({});
  const inFlightRef = useRef({});
  // One object-URL manager per URL-managed format (PDF alone), created once and
  // reused — switching formats never revokes a still-cached format's URL; only
  // Refresh, close and unmount do.
  const urlManagersRef = useRef(null);
  if (!urlManagersRef.current) {
    urlManagersRef.current = {};
    for (const f of URL_MANAGED_PREVIEW_FORMATS) {
      urlManagersRef.current[f] = createBlobPreviewUrlManager();
    }
  }

  const noteId = source?.noteId || null;
  const view = source?.view || null;
  const freeformEditor = source?.freeformEditor || null;
  const noteTitle = source?.noteTitle || "";

  const available = isFreeformPreviewAvailable(source);
  const entry = previewEntryFor(entries, format);
  const running = isPreviewRunning(entry);
  const ready = isPreviewReady(entry);
  const disabled = !available || running;

  const nextRequestId = (fmt) => {
    const next = (requestIdsRef.current[fmt] || 0) + 1;
    requestIdsRef.current[fmt] = next;
    return next;
  };

  // Revokes every managed object URL EXCEPT `exceptFormat`'s, so a Refresh of
  // the currently displayed format can keep showing it (still valid) until its
  // own new artifact replaces it.
  const releaseUrls = useCallback((exceptFormat = null) => {
    for (const f of URL_MANAGED_PREVIEW_FORMATS) {
      if (f === exceptFormat) continue;
      urlManagersRef.current[f].clear();
    }
  }, []);

  const generate = useCallback(
    (fmt, options = {}) => {
      if (!available) return;
      // Per-format synchronous duplicate guard: two selections of the same
      // format (or a format switch racing a Refresh of that same format) inside
      // one tick cannot both start a job.
      if (inFlightRef.current[fmt]) return;

      const snapshot = snapshotRef.current;
      if (!snapshot) return;

      const requestId = nextRequestId(fmt);
      inFlightRef.current[fmt] = true;

      // Applied to THIS format's entry unconditionally — never gated on which
      // format happens to be displayed, which is what silently dropped every
      // non-PDF generation before.
      setEntries((prev) =>
        beginPreviewFor(prev, {
          format: fmt,
          requestId,
          keepFile: !!options.keepFile,
        })
      );

      (async () => {
        let ok = false;
        let artifact = null;
        let message = "";
        try {
          artifact = await buildDocumentPreviewArtifact({
            format: fmt,
            snapshot,
            urlManager: urlManagersRef.current[fmt] || null,
          });
          // A producer that returned an artifact with nothing to show for its
          // own kind is a failure, not a blank preview.
          if (!isDisplayablePreviewArtifact(artifact)) {
            throw new Error(UNRENDERABLE);
          }
          ok = true;
        } catch (err) {
          ok = false;
          // Curated wording only. The existing Free-form export message already
          // explains a missing image or an unsplittable block and already
          // refuses to pass an unrecognised exception through; this names the
          // FORMAT that failed on top of it. An unrenderable artifact carries
          // no detail at all — there is nothing about it a user could act on
          // beyond retrying.
          message = documentPreviewFailureMessage(
            fmt,
            err && err.message === UNRENDERABLE
              ? ""
              : freeformExportFailureMessage(err)
          );
        } finally {
          // Released on every path, so a failed format can always be retried.
          inFlightRef.current[fmt] = false;
        }

        // STALE if: a newer job for this SAME format has started, the snapshot
        // has since been replaced (a Refresh ran, or the note/view changed), or
        // the component has unmounted. A stale job may neither settle an entry
        // nor touch an object URL a newer job may already own.
        const stale =
          requestIdsRef.current[fmt] !== requestId ||
          snapshotRef.current !== snapshot ||
          !mountedRef.current;
        if (stale) return;

        if (ok) {
          setEntries((prev) =>
            settlePreviewSuccessFor(prev, { format: fmt, requestId, file: artifact })
          );
        } else {
          setEntries((prev) =>
            settlePreviewFailureFor(prev, { format: fmt, requestId, message })
          );
        }
      })();
    },
    [available]
  );

  // Opening always captures a FRESH snapshot and drops every cached format —
  // the note may have changed since the dialog was last open — and PDF (the
  // default format) generates immediately.
  const handleOpen = useCallback(() => {
    if (!available) return;
    setOpen(true);
    setFormat(DOCUMENT_PREVIEW_FORMAT.PDF);
    snapshotRef.current = captureFreeformExportSnapshot({
      noteId,
      noteTitle,
      view,
      editor: freeformEditor,
    });
    releaseUrls();
    setEntries(createPreviewEntries());
    entriesRef.current = createPreviewEntries();
    generate(DOCUMENT_PREVIEW_FORMAT.PDF);
  }, [available, noteId, noteTitle, view, freeformEditor, releaseUrls, generate]);

  // Closing never cancels a job already in flight (a promise cannot be
  // cancelled) — it stops SHOWING it and releases every artifact and URL. The
  // job's own staleness guard (the snapshotRef comparison) is what stops it
  // from silently reopening the dialog when it completes: nothing below ever
  // calls `setOpen(true)`.
  const handleClose = useCallback(() => {
    setOpen(false);
    snapshotRef.current = null;
    releaseUrls();
    setEntries(createPreviewEntries());
    triggerRef.current?.focus();
  }, [releaseUrls]);

  // A format switch NEVER touches another format's entry or any object URL — it
  // only decides what to show. A cached artifact is redisplayed instantly with
  // no regeneration and no new URL; an uncached (or previously failed) format
  // starts its own generation.
  const handleSelectFormat = useCallback(
    (nextFormat) => {
      if (nextFormat === format) return;
      setFormat(nextFormat);
      if (shouldGeneratePreview(entriesRef.current, nextFormat)) {
        generate(nextFormat);
      }
    },
    [format, generate]
  );

  // A NEW snapshot, captured synchronously before any await — the same rule as
  // the initial open. Every cached format is invalidated (all were built from
  // the PREVIOUS snapshot); the currently displayed format keeps showing its
  // old artifact, and its still-valid URL, until the refresh completes.
  const handleRefresh = useCallback(() => {
    if (!available) return;
    const currentFormat = format;
    snapshotRef.current = captureFreeformExportSnapshot({
      noteId,
      noteTitle,
      view,
      editor: freeformEditor,
    });
    releaseUrls(currentFormat);
    const kept = invalidatePreviewEntries(entriesRef.current, {
      keepFormat: currentFormat,
    });
    setEntries(kept);
    entriesRef.current = kept;
    generate(currentFormat, { keepFile: true });
  }, [available, format, noteId, noteTitle, view, freeformEditor, releaseUrls, generate]);

  const handleDownload = useCallback(() => {
    // Reuses the Blob already held in the artifact — no regeneration, and never
    // the HTML approximation, which is a different field entirely.
    const artifact = entry.file;
    if (!artifact || !artifact.blob) return;
    downloadExportFile(artifact.filename, artifact.blob);
  }, [entry.file]);

  // A note or view switch retires the whole dialog outright, rather than
  // leaving it open with content that no longer belongs to what is now on
  // screen — "must not silently substitute another document" is satisfied most
  // simply by never showing a substituted one. Harmless no-op on mount and
  // whenever the dialog is already closed. A request still in flight keeps
  // running and is discarded as stale when it settles, because snapshotRef has
  // already been cleared here.
  useEffect(() => {
    setOpen(false);
    snapshotRef.current = null;
    releaseUrls();
    setEntries(createPreviewEntries());
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [noteId, view]);

  useEffect(() => {
    return () => {
      mountedRef.current = false;
      releaseUrls();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      <button
        ref={triggerRef}
        className={actionButtonClass({
          open,
          busy: running,
          disabled,
          className: "px-3 py-1.5 rounded-lg text-sm font-medium",
        })}
        onClick={handleOpen}
        disabled={disabled}
        title={
          !available
            ? "Document Preview is available for the Free-form note"
            : running
            ? "Generating the document preview…"
            : "Preview this note's exact exported document"
        }
        aria-label={running ? "Generating document preview…" : "Document Preview"}
        aria-haspopup="dialog"
        aria-busy={running}
      >
        {running ? "Generating…" : "Document Preview"}
      </button>

      <DocumentPreviewDialog
        open={open}
        noteTitle={noteTitle}
        format={format}
        formats={DOCUMENT_PREVIEW_FORMAT_ORDER}
        status={entry.status}
        message={entry.message}
        artifact={entry.file}
        onSelectFormat={handleSelectFormat}
        onClose={handleClose}
        onDownload={handleDownload}
        onRefresh={handleRefresh}
        canDownload={ready && !!entry.file?.blob}
        refreshDisabled={running || !available}
      />
    </>
  );
}
